import joblib
import pandas as pd

pipeline = joblib.load('student_model.pkl')
model = pipeline[-1]
# Get the feature names generated by your ColumnTransformer (One-Hot Encoding, etc.)
feature_names = pipeline[:-1].get_feature_names_out()

# Create a clean, readable DataFrame
weights_df = pd.DataFrame({
    'Feature': feature_names,
    'Weight': model.coef_
}).sort_values(by='Weight', ascending=False)

print(weights_df)